export const FoodDatabase = [
  // Proteins (Animal)
  { id: 1, name_en: "Chicken Breast", category: "Protein", calories_per_100g: 165, protein_per_100g: 31, carbs_per_100g: 0, fat_per_100g: 3.6, average_price_level: "medium", country_tags: ["global"], cuisine_tags: ["any"], diet_tags: ["high_protein", "low_carb", "anything"], allergy_tags: [], availability_tags: ["supermarket", "local_market"], common_meal_types: ["lunch", "dinner"] },
  { id: 2, name_en: "Eggs", category: "Protein", calories_per_100g: 143, protein_per_100g: 13, carbs_per_100g: 0.7, fat_per_100g: 9.5, average_price_level: "low", country_tags: ["global"], cuisine_tags: ["any"], diet_tags: ["vegetarian", "high_protein", "low_carb", "anything", "budget"], allergy_tags: ["eggs"], availability_tags: ["supermarket", "local_market", "budget_store"], common_meal_types: ["breakfast", "lunch", "dinner", "snack"] },
  { id: 3, name_en: "Salmon", category: "Protein", calories_per_100g: 208, protein_per_100g: 20, carbs_per_100g: 0, fat_per_100g: 13, average_price_level: "high", country_tags: ["global", "usa", "japan", "uk", "germany"], cuisine_tags: ["asian", "mediterranean"], diet_tags: ["high_protein", "low_carb", "mediterranean", "anything"], allergy_tags: ["fish"], availability_tags: ["supermarket", "premium_store"], common_meal_types: ["lunch", "dinner"] },
  { id: 4, name_en: "Tuna (Canned)", category: "Protein", calories_per_100g: 130, protein_per_100g: 28, carbs_per_100g: 0, fat_per_100g: 1, average_price_level: "low", country_tags: ["global", "usa", "uk"], cuisine_tags: ["any"], diet_tags: ["high_protein", "low_carb", "budget", "anything"], allergy_tags: ["fish"], availability_tags: ["supermarket", "budget_store"], common_meal_types: ["lunch", "snack"] },
  { id: 5, name_en: "Turkey Breast", category: "Protein", calories_per_100g: 135, protein_per_100g: 30, carbs_per_100g: 0, fat_per_100g: 1, average_price_level: "medium", country_tags: ["usa", "uk", "germany", "global"], cuisine_tags: ["any"], diet_tags: ["high_protein", "low_carb", "anything"], allergy_tags: [], availability_tags: ["supermarket"], common_meal_types: ["lunch", "dinner"] },
  { id: 6, name_en: "Beef (Lean)", category: "Protein", calories_per_100g: 250, protein_per_100g: 26, carbs_per_100g: 0, fat_per_100g: 15, average_price_level: "high", country_tags: ["usa", "uk", "france", "mexico", "global"], cuisine_tags: ["any"], diet_tags: ["high_protein", "low_carb", "anything"], allergy_tags: [], availability_tags: ["supermarket", "local_market"], common_meal_types: ["lunch", "dinner"] },
  { id: 7, name_en: "Chicken Thigh", category: "Protein", calories_per_100g: 209, protein_per_100g: 26, carbs_per_100g: 0, fat_per_100g: 10.9, average_price_level: "low", country_tags: ["global"], cuisine_tags: ["any"], diet_tags: ["high_protein", "low_carb", "budget", "anything"], allergy_tags: [], availability_tags: ["supermarket", "local_market"], common_meal_types: ["lunch", "dinner"] },
  { id: 8, name_en: "Shrimp", category: "Protein", calories_per_100g: 99, protein_per_100g: 24, carbs_per_100g: 0.2, fat_per_100g: 0.3, average_price_level: "high", country_tags: ["global", "japan", "usa", "mediterranean"], cuisine_tags: ["asian", "mediterranean"], diet_tags: ["high_protein", "low_carb", "mediterranean", "anything"], allergy_tags: ["shellfish"], availability_tags: ["supermarket", "premium_store"], common_meal_types: ["lunch", "dinner"] },

  // Proteins (Plant-Based)
  { id: 9, name_en: "Tofu", category: "Protein", calories_per_100g: 76, protein_per_100g: 8, carbs_per_100g: 1.9, fat_per_100g: 4.8, average_price_level: "medium", country_tags: ["japan", "south_korea", "china", "global"], cuisine_tags: ["asian"], diet_tags: ["vegan", "vegetarian", "asian", "anything"], allergy_tags: ["soy"], availability_tags: ["supermarket", "organic_store"], common_meal_types: ["lunch", "dinner"] },
  { id: 10, name_en: "Lentils", category: "Protein", calories_per_100g: 116, protein_per_100g: 9, carbs_per_100g: 20, fat_per_100g: 0.4, average_price_level: "low", country_tags: ["india", "middle_east", "germany", "turkey", "global"], cuisine_tags: ["indian", "middle_eastern"], diet_tags: ["vegan", "vegetarian", "budget", "anything"], allergy_tags: [], availability_tags: ["supermarket", "local_market", "budget_store"], common_meal_types: ["lunch", "dinner"] },
  { id: 11, name_en: "Chickpeas", category: "Protein", calories_per_100g: 164, protein_per_100g: 8.9, carbs_per_100g: 27, fat_per_100g: 2.6, average_price_level: "low", country_tags: ["middle_east", "india", "mediterranean", "global"], cuisine_tags: ["middle_eastern", "indian", "mediterranean"], diet_tags: ["vegan", "vegetarian", "mediterranean", "budget", "anything"], allergy_tags: [], availability_tags: ["supermarket", "local_market"], common_meal_types: ["lunch", "dinner", "snack"] },
  { id: 12, name_en: "Tempeh", category: "Protein", calories_per_100g: 193, protein_per_100g: 19, carbs_per_100g: 9, fat_per_100g: 11, average_price_level: "medium", country_tags: ["global", "indonesia"], cuisine_tags: ["asian"], diet_tags: ["vegan", "vegetarian", "high_protein", "anything"], allergy_tags: ["soy"], availability_tags: ["organic_store", "supermarket"], common_meal_types: ["lunch", "dinner"] },
  { id: 13, name_en: "Edamame", category: "Protein", calories_per_100g: 121, protein_per_100g: 11.9, carbs_per_100g: 8.9, fat_per_100g: 5.2, average_price_level: "medium", country_tags: ["japan", "global"], cuisine_tags: ["asian"], diet_tags: ["vegan", "vegetarian", "asian", "anything"], allergy_tags: ["soy"], availability_tags: ["supermarket"], common_meal_types: ["snack", "lunch"] },
  { id: 14, name_en: "Black Beans", category: "Protein", calories_per_100g: 132, protein_per_100g: 8.9, carbs_per_100g: 23.7, fat_per_100g: 0.5, average_price_level: "low", country_tags: ["mexico", "usa", "global"], cuisine_tags: ["mexican"], diet_tags: ["vegan", "vegetarian", "budget", "anything"], allergy_tags: [], availability_tags: ["supermarket", "budget_store"], common_meal_types: ["lunch", "dinner"] },
  { id: 15, name_en: "Kidney Beans", category: "Protein", calories_per_100g: 127, protein_per_100g: 8.7, carbs_per_100g: 22.8, fat_per_100g: 0.5, average_price_level: "low", country_tags: ["georgia", "mexico", "india", "global"], cuisine_tags: ["any"], diet_tags: ["vegan", "vegetarian", "budget", "anything"], allergy_tags: [], availability_tags: ["supermarket", "local_market"], common_meal_types: ["lunch", "dinner"] },

  // Grains & Carbs
  { id: 16, name_en: "White Rice", category: "Grains", calories_per_100g: 130, protein_per_100g: 2.7, carbs_per_100g: 28, fat_per_100g: 0.3, average_price_level: "low", country_tags: ["japan", "south_korea", "china", "india", "global"], cuisine_tags: ["asian", "indian"], diet_tags: ["vegan", "vegetarian", "asian", "budget", "anything"], allergy_tags: [], availability_tags: ["supermarket", "local_market", "budget_store"], common_meal_types: ["lunch", "dinner"] },
  { id: 17, name_en: "Brown Rice", category: "Grains", calories_per_100g: 111, protein_per_100g: 2.6, carbs_per_100g: 23, fat_per_100g: 0.9, average_price_level: "medium", country_tags: ["global"], cuisine_tags: ["any"], diet_tags: ["vegan", "vegetarian", "anything"], allergy_tags: [], availability_tags: ["supermarket"], common_meal_types: ["lunch", "dinner"] },
  { id: 18, name_en: "Oats", category: "Grains", calories_per_100g: 389, protein_per_100g: 16.9, carbs_per_100g: 66, fat_per_100g: 6.9, average_price_level: "low", country_tags: ["uk", "usa", "germany", "global"], cuisine_tags: ["any"], diet_tags: ["vegan", "vegetarian", "budget", "anything"], allergy_tags: ["gluten"], availability_tags: ["supermarket", "budget_store"], common_meal_types: ["breakfast", "snack"] },
  { id: 19, name_en: "Buckwheat", category: "Grains", calories_per_100g: 343, protein_per_100g: 13.2, carbs_per_100g: 71.5, fat_per_100g: 3.4, average_price_level: "low", country_tags: ["georgia", "russia", "global"], cuisine_tags: ["eastern_european"], diet_tags: ["vegan", "vegetarian", "budget", "anything"], allergy_tags: [], availability_tags: ["supermarket", "local_market"], common_meal_types: ["lunch", "dinner"] },
  { id: 20, name_en: "Potatoes", category: "Grains", calories_per_100g: 77, protein_per_100g: 2, carbs_per_100g: 17, fat_per_100g: 0.1, average_price_level: "low", country_tags: ["uk", "germany", "usa", "global"], cuisine_tags: ["any"], diet_tags: ["vegan", "vegetarian", "budget", "anything"], allergy_tags: [], availability_tags: ["supermarket", "local_market", "budget_store"], common_meal_types: ["lunch", "dinner"] },
  { id: 21, name_en: "Sweet Potatoes", category: "Grains", calories_per_100g: 86, protein_per_100g: 1.6, carbs_per_100g: 20, fat_per_100g: 0.1, average_price_level: "medium", country_tags: ["usa", "japan", "global"], cuisine_tags: ["any"], diet_tags: ["vegan", "vegetarian", "anything"], allergy_tags: [], availability_tags: ["supermarket", "local_market"], common_meal_types: ["lunch", "dinner"] },
  { id: 22, name_en: "Whole Wheat Bread", category: "Grains", calories_per_100g: 247, protein_per_100g: 13, carbs_per_100g: 41, fat_per_100g: 3.4, average_price_level: "medium", country_tags: ["usa", "uk", "germany", "global"], cuisine_tags: ["any"], diet_tags: ["vegan", "vegetarian", "anything"], allergy_tags: ["gluten"], availability_tags: ["supermarket"], common_meal_types: ["breakfast", "lunch", "snack"] },
  { id: 23, name_en: "Rye Bread", category: "Grains", calories_per_100g: 259, protein_per_100g: 9, carbs_per_100g: 48, fat_per_100g: 3.3, average_price_level: "medium", country_tags: ["germany", "georgia", "global"], cuisine_tags: ["european"], diet_tags: ["vegan", "vegetarian", "anything"], allergy_tags: ["gluten"], availability_tags: ["supermarket", "local_market"], common_meal_types: ["breakfast", "lunch", "dinner"] },
  { id: 24, name_en: "Pasta", category: "Grains", calories_per_100g: 131, protein_per_100g: 5, carbs_per_100g: 25, fat_per_100g: 1.1, average_price_level: "low", country_tags: ["italy", "global"], cuisine_tags: ["italian", "mediterranean"], diet_tags: ["vegan", "vegetarian", "mediterranean", "budget", "anything"], allergy_tags: ["gluten"], availability_tags: ["supermarket", "budget_store"], common_meal_types: ["lunch", "dinner"] },
  { id: 25, name_en: "Bulgur", category: "Grains", calories_per_100g: 83, protein_per_100g: 3.1, carbs_per_100g: 18.6, fat_per_100g: 0.2, average_price_level: "low", country_tags: ["turkey", "middle_east", "global"], cuisine_tags: ["middle_eastern", "mediterranean"], diet_tags: ["vegan", "vegetarian", "mediterranean", "budget", "anything"], allergy_tags: ["gluten"], availability_tags: ["supermarket", "local_market"], common_meal_types: ["lunch", "dinner"] },
  { id: 26, name_en: "Quinoa", category: "Grains", calories_per_100g: 120, protein_per_100g: 4.4, carbs_per_100g: 21.3, fat_per_100g: 1.9, average_price_level: "high", country_tags: ["global"], cuisine_tags: ["any"], diet_tags: ["vegan", "vegetarian", "anything"], allergy_tags: [], availability_tags: ["supermarket", "organic_store"], common_meal_types: ["lunch", "dinner"] },
  { id: 27, name_en: "Corn Tortillas", category: "Grains", calories_per_100g: 218, protein_per_100g: 6, carbs_per_100g: 45, fat_per_100g: 2.9, average_price_level: "low", country_tags: ["mexico", "usa", "global"], cuisine_tags: ["mexican"], diet_tags: ["vegan", "vegetarian", "budget", "anything"], allergy_tags: [], availability_tags: ["supermarket", "local_market"], common_meal_types: ["lunch", "dinner"] },
  { id: 28, name_en: "Lavash", category: "Grains", calories_per_100g: 260, protein_per_100g: 8, carbs_per_100g: 50, fat_per_100g: 1, average_price_level: "low", country_tags: ["georgia", "turkey", "middle_east"], cuisine_tags: ["middle_eastern"], diet_tags: ["vegan", "vegetarian", "budget", "anything"], allergy_tags: ["gluten"], availability_tags: ["local_market", "supermarket"], common_meal_types: ["lunch", "dinner"] },
  { id: 29, name_en: "Roti", category: "Grains", calories_per_100g: 297, protein_per_100g: 9.7, carbs_per_100g: 56, fat_per_100g: 3.7, average_price_level: "low", country_tags: ["india"], cuisine_tags: ["indian"], diet_tags: ["vegan", "vegetarian", "budget", "anything"], allergy_tags: ["gluten"], availability_tags: ["local_market", "supermarket"], common_meal_types: ["lunch", "dinner"] },
  { id: 30, name_en: "Noodles", category: "Grains", calories_per_100g: 138, protein_per_100g: 4.5, carbs_per_100g: 25, fat_per_100g: 2.1, average_price_level: "low", country_tags: ["japan", "south_korea", "china", "global"], cuisine_tags: ["asian"], diet_tags: ["vegan", "vegetarian", "asian", "budget", "anything"], allergy_tags: ["gluten"], availability_tags: ["supermarket"], common_meal_types: ["lunch", "dinner"] },

  // Dairy & Alternatives
  { id: 31, name_en: "Greek Yogurt", category: "Dairy", calories_per_100g: 59, protein_per_100g: 10, carbs_per_100g: 3.6, fat_per_100g: 0.4, average_price_level: "medium", country_tags: ["greece", "usa", "uk", "global"], cuisine_tags: ["mediterranean", "any"], diet_tags: ["vegetarian", "high_protein", "low_carb", "mediterranean", "anything"], allergy_tags: ["dairy"], availability_tags: ["supermarket"], common_meal_types: ["breakfast", "snack"] },
  { id: 32, name_en: "Matsoni", category: "Dairy", calories_per_100g: 65, protein_per_100g: 4, carbs_per_100g: 4, fat_per_100g: 3.5, average_price_level: "low", country_tags: ["georgia"], cuisine_tags: ["georgian"], diet_tags: ["vegetarian", "budget", "anything"], allergy_tags: ["dairy"], availability_tags: ["local_market", "supermarket"], common_meal_types: ["breakfast", "snack"] },
  { id: 33, name_en: "Quark", category: "Dairy", calories_per_100g: 73, protein_per_100g: 12, carbs_per_100g: 3, fat_per_100g: 0.2, average_price_level: "low", country_tags: ["germany", "russia"], cuisine_tags: ["european"], diet_tags: ["vegetarian", "high_protein", "low_carb", "budget", "anything"], allergy_tags: ["dairy"], availability_tags: ["supermarket"], common_meal_types: ["breakfast", "snack"] },
  { id: 34, name_en: "Cottage Cheese", category: "Dairy", calories_per_100g: 98, protein_per_100g: 11, carbs_per_100g: 3.4, fat_per_100g: 4.3, average_price_level: "medium", country_tags: ["usa", "uk", "germany", "global"], cuisine_tags: ["any"], diet_tags: ["vegetarian", "high_protein", "low_carb", "anything"], allergy_tags: ["dairy"], availability_tags: ["supermarket"], common_meal_types: ["breakfast", "snack"] },
  { id: 35, name_en: "Paneer", category: "Dairy", calories_per_100g: 321, protein_per_100g: 25, carbs_per_100g: 3.4, fat_per_100g: 25, average_price_level: "medium", country_tags: ["india"], cuisine_tags: ["indian"], diet_tags: ["vegetarian", "high_protein", "low_carb", "anything"], allergy_tags: ["dairy"], availability_tags: ["local_market", "supermarket"], common_meal_types: ["lunch", "dinner"] },
  { id: 36, name_en: "Milk", category: "Dairy", calories_per_100g: 42, protein_per_100g: 3.4, carbs_per_100g: 5, fat_per_100g: 1, average_price_level: "low", country_tags: ["global"], cuisine_tags: ["any"], diet_tags: ["vegetarian", "budget", "anything"], allergy_tags: ["dairy"], availability_tags: ["supermarket", "budget_store", "local_market"], common_meal_types: ["breakfast", "snack"] },
  { id: 37, name_en: "Soy Milk", category: "Dairy", calories_per_100g: 33, protein_per_100g: 3.3, carbs_per_100g: 1.8, fat_per_100g: 1.5, average_price_level: "medium", country_tags: ["global", "japan"], cuisine_tags: ["any"], diet_tags: ["vegan", "vegetarian", "asian", "anything"], allergy_tags: ["soy"], availability_tags: ["supermarket"], common_meal_types: ["breakfast", "snack"] },
  { id: 38, name_en: "Almond Milk", category: "Dairy", calories_per_100g: 15, protein_per_100g: 0.5, carbs_per_100g: 0.3, fat_per_100g: 1.2, average_price_level: "medium", country_tags: ["global", "usa"], cuisine_tags: ["any"], diet_tags: ["vegan", "vegetarian", "low_carb", "anything"], allergy_tags: ["nuts"], availability_tags: ["supermarket"], common_meal_types: ["breakfast", "snack"] },
  { id: 39, name_en: "Cheese", category: "Dairy", calories_per_100g: 402, protein_per_100g: 25, carbs_per_100g: 1.3, fat_per_100g: 33, average_price_level: "medium", country_tags: ["france", "italy", "uk", "usa", "global"], cuisine_tags: ["european", "mediterranean"], diet_tags: ["vegetarian", "low_carb", "anything"], allergy_tags: ["dairy"], availability_tags: ["supermarket", "local_market"], common_meal_types: ["lunch", "snack"] },
  
  // Vegetables
  { id: 40, name_en: "Tomatoes", category: "Vegetables", calories_per_100g: 18, protein_per_100g: 0.9, carbs_per_100g: 3.9, fat_per_100g: 0.2, average_price_level: "low", country_tags: ["global", "italy", "mexico", "turkey"], cuisine_tags: ["any", "mediterranean"], diet_tags: ["vegan", "vegetarian", "low_carb", "mediterranean", "budget", "anything"], allergy_tags: [], availability_tags: ["supermarket", "local_market"], common_meal_types: ["lunch", "dinner", "snack"] },
  { id: 41, name_en: "Cucumbers", category: "Vegetables", calories_per_100g: 15, protein_per_100g: 0.7, carbs_per_100g: 3.6, fat_per_100g: 0.1, average_price_level: "low", country_tags: ["global", "georgia", "turkey", "middle_east"], cuisine_tags: ["any", "mediterranean"], diet_tags: ["vegan", "vegetarian", "low_carb", "mediterranean", "budget", "anything"], allergy_tags: [], availability_tags: ["supermarket", "local_market"], common_meal_types: ["lunch", "dinner", "snack"] },
  { id: 42, name_en: "Spinach", category: "Vegetables", calories_per_100g: 23, protein_per_100g: 2.9, carbs_per_100g: 3.6, fat_per_100g: 0.4, average_price_level: "medium", country_tags: ["global"], cuisine_tags: ["any"], diet_tags: ["vegan", "vegetarian", "low_carb", "mediterranean", "anything"], allergy_tags: [], availability_tags: ["supermarket", "local_market"], common_meal_types: ["lunch", "dinner"] },
  { id: 43, name_en: "Broccoli", category: "Vegetables", calories_per_100g: 34, protein_per_100g: 2.8, carbs_per_100g: 6.6, fat_per_100g: 0.4, average_price_level: "medium", country_tags: ["global", "usa", "uk"], cuisine_tags: ["any"], diet_tags: ["vegan", "vegetarian", "low_carb", "anything"], allergy_tags: [], availability_tags: ["supermarket"], common_meal_types: ["lunch", "dinner"] },
  { id: 44, name_en: "Cabbage", category: "Vegetables", calories_per_100g: 25, protein_per_100g: 1.3, carbs_per_100g: 5.8, fat_per_100g: 0.1, average_price_level: "low", country_tags: ["global", "germany", "south_korea"], cuisine_tags: ["any"], diet_tags: ["vegan", "vegetarian", "low_carb", "budget", "anything"], allergy_tags: [], availability_tags: ["supermarket", "local_market"], common_meal_types: ["lunch", "dinner"] },
  { id: 45, name_en: "Carrots", category: "Vegetables", calories_per_100g: 41, protein_per_100g: 0.9, carbs_per_100g: 9.6, fat_per_100g: 0.2, average_price_level: "low", country_tags: ["global"], cuisine_tags: ["any"], diet_tags: ["vegan", "vegetarian", "budget", "anything"], allergy_tags: [], availability_tags: ["supermarket", "local_market"], common_meal_types: ["lunch", "dinner", "snack"] },
  { id: 46, name_en: "Bell Peppers", category: "Vegetables", calories_per_100g: 31, protein_per_100g: 1, carbs_per_100g: 6, fat_per_100g: 0.3, average_price_level: "medium", country_tags: ["global", "mexico", "spain"], cuisine_tags: ["any", "mediterranean"], diet_tags: ["vegan", "vegetarian", "low_carb", "mediterranean", "anything"], allergy_tags: [], availability_tags: ["supermarket", "local_market"], common_meal_types: ["lunch", "dinner"] },
  { id: 47, name_en: "Mushrooms", category: "Vegetables", calories_per_100g: 22, protein_per_100g: 3.1, carbs_per_100g: 3.3, fat_per_100g: 0.3, average_price_level: "medium", country_tags: ["global", "france"], cuisine_tags: ["any"], diet_tags: ["vegan", "vegetarian", "low_carb", "anything"], allergy_tags: [], availability_tags: ["supermarket", "local_market"], common_meal_types: ["lunch", "dinner"] },
  { id: 48, name_en: "Onions", category: "Vegetables", calories_per_100g: 40, protein_per_100g: 1.1, carbs_per_100g: 9.3, fat_per_100g: 0.1, average_price_level: "low", country_tags: ["global"], cuisine_tags: ["any"], diet_tags: ["vegan", "vegetarian", "budget", "anything"], allergy_tags: [], availability_tags: ["supermarket", "local_market"], common_meal_types: ["lunch", "dinner"] },
  { id: 49, name_en: "Seaweed", category: "Vegetables", calories_per_100g: 43, protein_per_100g: 3.1, carbs_per_100g: 9.1, fat_per_100g: 0.6, average_price_level: "medium", country_tags: ["japan", "south_korea"], cuisine_tags: ["asian"], diet_tags: ["vegan", "vegetarian", "low_carb", "asian", "anything"], allergy_tags: [], availability_tags: ["supermarket", "asian_market"], common_meal_types: ["lunch", "dinner", "snack"] },
  { id: 50, name_en: "Kimchi", category: "Vegetables", calories_per_100g: 15, protein_per_100g: 1.1, carbs_per_100g: 2.4, fat_per_100g: 0.5, average_price_level: "medium", country_tags: ["south_korea"], cuisine_tags: ["asian"], diet_tags: ["vegan", "vegetarian", "low_carb", "asian", "anything"], allergy_tags: [], availability_tags: ["supermarket", "asian_market"], common_meal_types: ["lunch", "dinner"] },

  // Fruits
  { id: 51, name_en: "Apples", category: "Fruits", calories_per_100g: 52, protein_per_100g: 0.3, carbs_per_100g: 14, fat_per_100g: 0.2, average_price_level: "low", country_tags: ["global", "germany", "usa", "uk"], cuisine_tags: ["any"], diet_tags: ["vegan", "vegetarian", "budget", "anything"], allergy_tags: [], availability_tags: ["supermarket", "local_market"], common_meal_types: ["breakfast", "snack"] },
  { id: 52, name_en: "Bananas", category: "Fruits", calories_per_100g: 89, protein_per_100g: 1.1, carbs_per_100g: 23, fat_per_100g: 0.3, average_price_level: "low", country_tags: ["global"], cuisine_tags: ["any"], diet_tags: ["vegan", "vegetarian", "budget", "anything"], allergy_tags: [], availability_tags: ["supermarket", "local_market", "budget_store"], common_meal_types: ["breakfast", "snack"] },
  { id: 53, name_en: "Berries", category: "Fruits", calories_per_100g: 57, protein_per_100g: 0.7, carbs_per_100g: 14, fat_per_100g: 0.3, average_price_level: "high", country_tags: ["global", "usa", "uk"], cuisine_tags: ["any"], diet_tags: ["vegan", "vegetarian", "low_carb", "anything"], allergy_tags: [], availability_tags: ["supermarket", "premium_store"], common_meal_types: ["breakfast", "snack"] },
  { id: 54, name_en: "Oranges", category: "Fruits", calories_per_100g: 47, protein_per_100g: 0.9, carbs_per_100g: 12, fat_per_100g: 0.1, average_price_level: "low", country_tags: ["global", "spain"], cuisine_tags: ["any"], diet_tags: ["vegan", "vegetarian", "budget", "anything"], allergy_tags: [], availability_tags: ["supermarket", "local_market"], common_meal_types: ["breakfast", "snack"] },

  // Fats
  { id: 55, name_en: "Olive Oil", category: "Fats", calories_per_100g: 884, protein_per_100g: 0, carbs_per_100g: 0, fat_per_100g: 100, average_price_level: "medium", country_tags: ["italy", "spain", "greece", "global"], cuisine_tags: ["mediterranean", "any"], diet_tags: ["vegan", "vegetarian", "low_carb", "mediterranean", "anything"], allergy_tags: [], availability_tags: ["supermarket"], common_meal_types: ["lunch", "dinner"] },
  { id: 56, name_en: "Sunflower Oil", category: "Fats", calories_per_100g: 884, protein_per_100g: 0, carbs_per_100g: 0, fat_per_100g: 100, average_price_level: "low", country_tags: ["russia", "georgia", "global"], cuisine_tags: ["any"], diet_tags: ["vegan", "vegetarian", "low_carb", "budget", "anything"], allergy_tags: [], availability_tags: ["supermarket", "budget_store"], common_meal_types: ["lunch", "dinner"] },
  { id: 57, name_en: "Avocado", category: "Fats", calories_per_100g: 160, protein_per_100g: 2, carbs_per_100g: 8.5, fat_per_100g: 14.7, average_price_level: "high", country_tags: ["mexico", "usa", "global"], cuisine_tags: ["mexican", "mediterranean"], diet_tags: ["vegan", "vegetarian", "low_carb", "mediterranean", "anything"], allergy_tags: [], availability_tags: ["supermarket", "premium_store"], common_meal_types: ["breakfast", "lunch", "dinner", "snack"] },
  { id: 58, name_en: "Nuts (Mixed)", category: "Fats", calories_per_100g: 607, protein_per_100g: 20, carbs_per_100g: 21, fat_per_100g: 54, average_price_level: "high", country_tags: ["global"], cuisine_tags: ["any"], diet_tags: ["vegan", "vegetarian", "low_carb", "mediterranean", "anything"], allergy_tags: ["nuts"], availability_tags: ["supermarket"], common_meal_types: ["snack", "breakfast"] },
  { id: 59, name_en: "Peanut Butter", category: "Fats", calories_per_100g: 588, protein_per_100g: 25, carbs_per_100g: 20, fat_per_100g: 50, average_price_level: "medium", country_tags: ["usa", "uk", "global"], cuisine_tags: ["any"], diet_tags: ["vegan", "vegetarian", "high_protein", "anything"], allergy_tags: ["nuts"], availability_tags: ["supermarket"], common_meal_types: ["breakfast", "snack"] },
  { id: 60, name_en: "Olives", category: "Fats", calories_per_100g: 115, protein_per_100g: 0.8, carbs_per_100g: 6.3, fat_per_100g: 10.7, average_price_level: "medium", country_tags: ["italy", "greece", "turkey", "global"], cuisine_tags: ["mediterranean"], diet_tags: ["vegan", "vegetarian", "low_carb", "mediterranean", "anything"], allergy_tags: [], availability_tags: ["supermarket", "local_market"], common_meal_types: ["lunch", "snack"] },

  // Spices & Other
  { id: 61, name_en: "Miso Paste", category: "Spices", calories_per_100g: 199, protein_per_100g: 12, carbs_per_100g: 25, fat_per_100g: 6, average_price_level: "medium", country_tags: ["japan"], cuisine_tags: ["asian"], diet_tags: ["vegan", "vegetarian", "asian", "anything"], allergy_tags: ["soy"], availability_tags: ["supermarket", "asian_market"], common_meal_types: ["breakfast", "lunch", "dinner"] },
  { id: 62, name_en: "Soy Sauce", category: "Spices", calories_per_100g: 53, protein_per_100g: 8, carbs_per_100g: 4.9, fat_per_100g: 0.1, average_price_level: "low", country_tags: ["japan", "china", "south_korea", "global"], cuisine_tags: ["asian"], diet_tags: ["vegan", "vegetarian", "asian", "budget", "anything"], allergy_tags: ["soy", "gluten"], availability_tags: ["supermarket"], common_meal_types: ["lunch", "dinner"] }

  // More can be added as needed, but this is a solid 62-item starting DB covering all requirements.
];

export const getFoodsByLocation = (country, city) => {
  // A simplistic filter that gives a score to each food based on tags
  // We'll use this in mealGenerator
  if (country || city) {
    // Future expansion: filter by location tags
  }
  return FoodDatabase;
};
